### ISSUE TITLE
Reproduce 

### ISSUE THREAD

**Issue by zed-2018** [danielzuegner/netgan#1]
I follow this code to train the results of Graph Generation that can't reproduce your paper. Do you have any other settings?

**Comment by danielzuegner** [comment]
Hi,

Can you specify which results you are aiming to reproduce? Note that due to the many sources of stochasticity involved, minor deviations to the results in the paper can be expected.

**Comment by zed-2018** [comment]
Hi, I just trained the graph generation of cora_ml according to this code, but regardless of the iteration 50k or 100k, the edge overlap always oscillates around 0.4, and does not continue to rise to 0.5 or higher like this picture.
<img width="294" alt="2018-07-25 3 16 37" src="https://user-images.githubusercontent.com/37239581/43185235-e317a1ee-901d-11e8-8418-97a1ae33c096.png">

**Comment by zed-2018** [comment]
Hi, How can I calculate the Table 1 .Average rank?

**Comment by danielzuegner** [comment]
Hi,

regarding the edge overlap: please update the project and try again -- I've trained NetGAN today with EO criterion and could reach >50% edge overlap.

Regarding the average rank: This is the aggregation of all other results, i.e. we rank for each statistic all methods by how close they are to the original graph, and then average these ranks in order to have a single number to compare the methods.

Please let me know in case you have any other questions.

**Comment by zed-2018** [comment]
I understand, thank you very much for your patience.
